package store;
import java.text.DecimalFormat;

public class VentanaDescripcion extends javax.swing.JFrame {

    
    public VentanaDescripcion(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Detalles de venta");
        this.setResizable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtArticulo1 = new javax.swing.JLabel();
        txtArticulo2 = new javax.swing.JLabel();
        txtArticulo3 = new javax.swing.JLabel();
        txtArticulo4 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JLabel();
        txtCantidad3 = new javax.swing.JLabel();
        txtCantidad4 = new javax.swing.JLabel();
        txtPrecioSinIVA1 = new javax.swing.JLabel();
        txtPrecioSinIVA2 = new javax.swing.JLabel();
        txtPrecioSinIVA3 = new javax.swing.JLabel();
        txtPrecioSinIVA4 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JLabel();
        txtPrecio3 = new javax.swing.JLabel();
        txtPrecio4 = new javax.swing.JLabel();
        txtDescuento1 = new javax.swing.JLabel();
        txtDescuento2 = new javax.swing.JLabel();
        txtDescuento3 = new javax.swing.JLabel();
        txtDescuento4 = new javax.swing.JLabel();
        txtPagar1 = new javax.swing.JLabel();
        txtPagar2 = new javax.swing.JLabel();
        txtPagar3 = new javax.swing.JLabel();
        txtPagar4 = new javax.swing.JLabel();
        btRegresar = new javax.swing.JButton();
        btPagar = new javax.swing.JButton();
        txtTotalPagar = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtPago = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Facturación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Productos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Precio + IVA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Descuento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total a pagar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        txtArticulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo1.setText("Pan");
        getContentPane().add(txtArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        txtArticulo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo2.setText("Galleta");
        getContentPane().add(txtArticulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        txtArticulo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo3.setText("Azucar");
        getContentPane().add(txtArticulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, -1));

        txtArticulo4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtArticulo4.setText("Coca cola");
        getContentPane().add(txtArticulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        txtCantidad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad1.setText("0");
        getContentPane().add(txtCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 50, -1));

        txtCantidad2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad2.setText("0");
        getContentPane().add(txtCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 50, -1));

        txtCantidad3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad3.setText("0");
        getContentPane().add(txtCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, -1));

        txtCantidad4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCantidad4.setText("0");
        getContentPane().add(txtCantidad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, -1));

        txtPrecioSinIVA1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecioSinIVA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecioSinIVA1.setText("Q0");
        getContentPane().add(txtPrecioSinIVA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 60, -1));

        txtPrecioSinIVA2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecioSinIVA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecioSinIVA2.setText("Q0");
        getContentPane().add(txtPrecioSinIVA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 60, -1));

        txtPrecioSinIVA3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecioSinIVA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecioSinIVA3.setText("Q0");
        getContentPane().add(txtPrecioSinIVA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 60, -1));

        txtPrecioSinIVA4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecioSinIVA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecioSinIVA4.setText("Q0");
        getContentPane().add(txtPrecioSinIVA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 60, -1));

        txtPrecio1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio1.setText("Q0");
        getContentPane().add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 60, -1));

        txtPrecio2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio2.setText("Q0");
        getContentPane().add(txtPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 60, -1));

        txtPrecio3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio3.setText("Q0");
        getContentPane().add(txtPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 60, -1));

        txtPrecio4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio4.setText("Q0");
        getContentPane().add(txtPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 60, -1));

        txtDescuento1.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento1.setText("Q0");
        getContentPane().add(txtDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 70, -1));

        txtDescuento2.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento2.setText("Q0");
        getContentPane().add(txtDescuento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 70, -1));

        txtDescuento3.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento3.setText("Q0");
        getContentPane().add(txtDescuento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 70, -1));

        txtDescuento4.setBackground(new java.awt.Color(255, 255, 255));
        txtDescuento4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDescuento4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDescuento4.setText("Q0");
        getContentPane().add(txtDescuento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 70, -1));

        txtPagar1.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar1.setText("Q0");
        getContentPane().add(txtPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 80, -1));

        txtPagar2.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar2.setText("Q0");
        getContentPane().add(txtPagar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 80, -1));

        txtPagar3.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar3.setText("Q0");
        getContentPane().add(txtPagar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 80, -1));

        txtPagar4.setBackground(new java.awt.Color(255, 255, 255));
        txtPagar4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPagar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPagar4.setText("Q0");
        getContentPane().add(txtPagar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 80, -1));

        btRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 130, -1));

        btPagar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btPagar.setText("Pagar");
        btPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 140, -1));

        txtTotalPagar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTotalPagar.setText("Q0");
        getContentPane().add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 110, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("TOTAL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "PAYPAL", "T. CREDITO" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));
        getContentPane().add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagarActionPerformed
        // TODO add your handling code here:
        
        TipoPago tp = new TipoPago();
        tp.setVisible(true);
        tp.setLocationRelativeTo(null);
         
    
    }//GEN-LAST:event_btPagarActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        Menu ventana2 = new Menu();
        this.setVisible(false);
        ventana2.setVisible(true);
    }//GEN-LAST:event_btRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDescripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDescripcion().setVisible(true);
            }
        });
    }
    public void cantidades(String cantidad1, String cantidad2, String cantidad3, String cantidad4){
        DecimalFormat df = new DecimalFormat("#.##");
        //Cantidad
        txtCantidad1.setText(cantidad1);
        txtCantidad2.setText(cantidad2);
        txtCantidad3.setText(cantidad3);
        txtCantidad4.setText(cantidad4);
        
        //precios
        txtPrecioSinIVA1.setText("Q2");
        txtPrecioSinIVA2.setText("Q3");
        txtPrecioSinIVA3.setText("Q2.50");
        txtPrecioSinIVA4.setText("Q6");
        //precios + iva
        float p1 = 2.0f + (2.0f*0.12f);
        float p2 = 3.00f + (3.0f*0.12f);
        float p3 = 2.50f + (2.50f*0.12f);
        float p4 = 6.0f + (6.0f*0.12f);
        
        String prec1 = df.format(p1);
        String prec2 = df.format(p2);
        String prec3 = df.format(p3);
        String prec4 = df.format(p4);
        
        txtPrecio1.setText("Q"+prec1);
        txtPrecio2.setText("Q"+prec2);
        txtPrecio3.setText("Q"+prec3);
        txtPrecio4.setText("Q"+prec4);
        // descuentos
        int cantidadp1 = Integer.parseInt(cantidad1);
        int cantidadp2 = Integer.parseInt(cantidad2);
        int cantidadp3 = Integer.parseInt(cantidad3);
        int cantidadp4 = Integer.parseInt(cantidad4);
        
        int cDescuentos;
        float aPagar1;
        float aPagar2;
        float aPagar3;
        float aPagar4;
        
        //En este apartado calculamos los desceuntos para productos que superen la cantidad de 3
        
        
        if(cantidadp1>=3){          
            if(cantidadp1==3){ 
                String descuento= df.format(p1);
                float cantidadF = Float.valueOf(cantidadp1);
                aPagar1= (cantidadF-1f)*p1;
                String total1 = df.format(aPagar1);
                txtDescuento1.setText("Q"+descuento);
                txtPagar1.setText("Q"+total1);
               
            }else{
                cDescuentos = (cantidadp1/3);
                int cantidad= cantidadp1-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p1*cDescuentos;
                aPagar1= p1*cantidadP;
                
                String descuento= df.format(desc);
                txtDescuento1.setText("Q"+descuento);
                
                String total1= df.format(aPagar1);
                txtPagar1.setText("Q"+total1);
                
            }
        }else{
            float cant1= Float.valueOf(cantidadp1);
            aPagar1= p1*cant1;
            String total1= String.valueOf(aPagar1);
            txtPagar1.setText("Q"+total1);
        }
        if(cantidadp2>=3){          
            if(cantidadp2==3){ 
                String descuento= df.format(p2);
                float cantidadF = Float.valueOf(cantidadp2);
                aPagar2= (cantidadF-1f)*p2;
                String total2 = df.format(aPagar2);
                txtDescuento2.setText("Q"+descuento);
                txtPagar2.setText("Q"+total2); 
            }else{
                cDescuentos = (cantidadp2/3);
                int cantidad= cantidadp2-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p2*cDescuentos;
                aPagar2= p2*cantidadP;
                
                String descuento= df.format(desc);
                txtDescuento2.setText("Q"+descuento);
                
                String total2= df.format(aPagar2);
                txtPagar2.setText("Q"+total2);
                
            }
        }else{
            float cant2= Float.valueOf(cantidadp2);
            aPagar2= p2*cant2;
            String total2= String.valueOf(aPagar2);
            txtPagar2.setText("Q"+total2);
        }
        if(cantidadp3>=3){          
            if(cantidadp3==3){ 
                String descuento= df.format(p3);
                float cantidadF = Float.valueOf(cantidadp3);
                aPagar3= (cantidadF-1f)*p3;
                String total3 = df.format(aPagar3);
                txtDescuento3.setText("Q"+descuento);
                txtPagar3.setText("Q"+total3);
            }else{
                cDescuentos = (cantidadp3/3);
                int cantidad= cantidadp3-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p3*cDescuentos;
                aPagar3= p3*cantidadP;
                
                String total3= df.format(desc);
                txtDescuento3.setText("Q"+total3);
                
                String descuentoTotal= df.format(aPagar3);
                txtPagar3.setText("Q"+descuentoTotal);
                
            }
        }else{
            float cant3= Float.valueOf(cantidadp3);
            aPagar3= p3*cant3;
            String total3= String.valueOf(aPagar3);
            txtPagar3.setText("Q"+total3);
        }
        if(cantidadp4>=3){          
            if(cantidadp4==3){ 
                String descuento= df.format(p4);
                float cantidadF = Float.valueOf(cantidadp4);
                aPagar4= (cantidadF-1f)*p4;
                String total4 = df.format(aPagar4);
                txtDescuento4.setText("Q"+descuento);
                txtPagar4.setText("Q"+total4);
            }else{
                cDescuentos = (cantidadp4/3);
                int cantidad= cantidadp4-(cDescuentos);
                float cantidadP= Float.valueOf(cantidad);
                
                float desc= p4*cDescuentos;
                aPagar4= p4*cantidadP;
                
                String descuento= df.format(desc);
                txtDescuento4.setText("Q"+descuento);
                
                String total4= df.format(aPagar4);
                txtPagar4.setText("Q"+total4);
                
            }
        }else{
            float cant4= Float.valueOf(cantidadp4);
            aPagar4= p4*cant4;
            String total4= df.format(aPagar4);
            txtPagar4.setText("Q"+total4);
        }
        
        float pagoTotal= aPagar1 + aPagar2 + aPagar3 + aPagar4;
        String pagoTotalS = df.format(pagoTotal);
        txtTotalPagar.setText(pagoTotalS);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPagar;
    private javax.swing.JButton btRegresar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel txtArticulo1;
    private javax.swing.JLabel txtArticulo2;
    private javax.swing.JLabel txtArticulo3;
    private javax.swing.JLabel txtArticulo4;
    private javax.swing.JLabel txtCantidad1;
    private javax.swing.JLabel txtCantidad2;
    private javax.swing.JLabel txtCantidad3;
    private javax.swing.JLabel txtCantidad4;
    private javax.swing.JLabel txtDescuento1;
    private javax.swing.JLabel txtDescuento2;
    private javax.swing.JLabel txtDescuento3;
    private javax.swing.JLabel txtDescuento4;
    private javax.swing.JLabel txtPagar1;
    private javax.swing.JLabel txtPagar2;
    private javax.swing.JLabel txtPagar3;
    private javax.swing.JLabel txtPagar4;
    private javax.swing.JTextField txtPago;
    private javax.swing.JLabel txtPrecio1;
    private javax.swing.JLabel txtPrecio2;
    private javax.swing.JLabel txtPrecio3;
    private javax.swing.JLabel txtPrecio4;
    private javax.swing.JLabel txtPrecioSinIVA1;
    private javax.swing.JLabel txtPrecioSinIVA2;
    private javax.swing.JLabel txtPrecioSinIVA3;
    private javax.swing.JLabel txtPrecioSinIVA4;
    public static javax.swing.JLabel txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
